server:
  port: 9090
spring:
  cloud:
    gateway:
      routes:
        # 下面这段配置的意思是，配置了一个 id 为 login 的路由规则，
        # 当访问地址 http://localhost:9090/login/** 时会自动转发到地址：http://localhost:8090/login/**
        - id: login # 路由 ID，保持唯一
          # 目标服务地址
          uri: http://localhost:8090
          # 路由条件
          predicates:
            - Path=/login/**
