server:
  port: 9090

spring:
  application:
    name: component-gateway

  cloud:
    gateway:
      discovery:
        locator:
          enabled: true # 开启从注册中心动态创建路由的功能，利用微服务名进行路由
      routes:
        # 下面这段配置的意思是，配置了一个 id 为 login 的路由规则，
        # 当访问地址 http://localhost:9090/login/** 时会自动转发到地址：http://localhost:8090/login/**
        - id: login # 路由 ID，保持唯一
          # uri: http://localhost:8090 # 目标服务地址
          uri: lb://service-web
          predicates: # 断言，结果为true的进行路由
            - Path=/login/**
            - After=2021-04-11T21:00:18.497693+08:00[Asia/Shanghai]
          # filters: # 配置过滤器

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8080/eureka
  instance:
    prefer-ip-address: true # 当调用 getHostname 获取实例的 hostname 时，返回 IP 而不是 host 名称
    ip-address: 127.0.0.1 # 指定自己的 IP ，不指定的话会自己寻找
    lease-expiration-duration-in-seconds: 10 # 服务失效时间，默认为90秒
    lease-renewal-interval-in-seconds: 5 # 服务续约的间隔，默认为30秒
