server:
  port: 8081

spring:
  application:
    name: component-config

  cloud:
    # 配置中心
    config:
      server:
        git:
          uri: https://github.com/ZGW-GitHub/StudyCode.git
          search-paths:
            - Frame/SpringCloud/component-config/src/main/resources/config
      label: master

# 消息总线
rocketmq:
  name-server: linux.juststudy.site:9876

# 暴露监控端点
management:
  endpoints:
    web:
      exposure:
        include: 'bus-refresh'

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8080/eureka
  instance:
    prefer-ip-address: true # 当调用 getHostname 获取实例的 hostname 时，返回 IP 而不是 host 名称
    ip-address: 127.0.0.1 # 指定自己的 IP ，不指定的话会自己寻找
    lease-expiration-duration-in-seconds: 10 # 服务失效时间，默认为90秒
    lease-renewal-interval-in-seconds: 5 # 服务续约的间隔，默认为30秒
