server:
  port: 8091

spring:
  application:
    name: service-user

  cloud:
    # Spring Cloud Stream 配置
    stream:
      binders: # 配置 MQ 的信息
        defaultMQ: # 表示定义的名称，用于与 binding 整合
          type: rocket # 消息组件类型
          environment:
            spring:
              rocketmq:
                name-server: 10.10.10.24:9876
      bindings: # 服务的整合处理
        input: # 这个名字是一个通道的名称
          destination: StudyExchange # 表示要使用的 Exchange 的名称定义
          content-type: application/json # 设置消息类型
          binder: defaultRabbit # 设置要绑定的消息服务的具体位置
          group: Group-A
