server:
  port: 8090

spring:
  application:
    name: service-web

  cloud:
    # 配置中心
    config:
      label: master
      name: config
      profile: dev
      uri: http://localhost:8081

    # Spring Cloud Stream 配置
    stream:
      binders: # 配置 MQ 的信息
        defaultMQ: # 表示定义的名称，用于与 binding 整合
          type: rocket # 消息组件类型
          environment:
            spring:
              rocketmq:
                name-server: linux.notuptoyou.site:9876
      bindings: # 服务的整合处理
        output: # 这个名字是一个通道的名称
          destination: StudyExchange # 表示要使用的 Exchange 的名称定义
          content-type: application/json # 设置消息类型
          binder: defaultRabbit # 设置要绑定的消息服务的具体位置

# 消息总线
rocketmq:
  name-server: linux.notuptoyou.site:9876

# 暴露监控端点
management:
  endpoints:
    web:
      exposure:
        include: "*"

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8080/eureka
  instance:
    prefer-ip-address: true # 当调用 getHostname 获取实例的 hostname 时，返回 IP 而不是 host 名称
    ip-address: 127.0.0.1 # 指定自己的 IP ，不指定的话会自己寻找
    lease-expiration-duration-in-seconds: 10 # 服务失效时间，默认为90秒
    lease-renewal-interval-in-seconds: 5 # 服务续约的间隔，默认为30秒
